# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  chrome-node-1:
    image: selenium/node-chrome:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6901:5900"
      - "7901:7900"

  chrome-node-2:
    image: selenium/node-chrome:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6902:5900"
      - "7902:7900"

  chrome-node-3:
    image: selenium/node-chrome:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6903:5900"
      - "7903:7900"


  edge:
    image: selenium/node-edge:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6904:5900"
      - "7904:7900"

  firefox:
    image: selenium/node-firefox:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6905:5900"
      - "7905:7900"

  opera:
    image: selenium/node-opera:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6906:5900"
      - "7906:7900"

#  appium:
#    privileged: true
#    ports:
#      - '4723:4723'
#    depends_on:
#      - selenium-hub
#    environment:
#      - CONNECT_TO_GRID=true
#      - APPIUM_HOST=127.0.0.1
#      - APPIUM_PORT=4723
#      - SELENIUM_HOST=selenium-hub
#      - SELENIUM_PORT=4444
#    volumes:
#      - '/dev/bus/usb:/dev/bus/usb'
#    container_name: container-appium
#    image: appium/appium

  selenium-hub:
    image: selenium/hub:4.0.0-beta-3-20210426
    container_name: selenium-hub
    environment:
      - NODE_MAX_INSTANCES=5
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
